### ISSUE TITLE
Merge common dependent packages into the framework

### ISSUE THREAD

**Issue by iharsuvorau** [AutomatedProcessImprovement/pix-framework#2]
These are currently published PIX libraries, https://pypi.org/user/pix/. 

The problem I'm facing often is with updating each others' versions. For example, a bug is fixed in pix-framework. Now, all the dependent packages (https://github.com/AutomatedProcessImprovement/pix-framework/network/dependents?dependent_type=PACKAGE) have to be updated. But, they can be updated **only in a certain order** because of inter-dependencies.

@david-chapela Would it make sense to merge start-time-estimator, extraneous-activity-delays, case-attribute-discovery into the framework, into pix-framework.discovery for example?

**Comment by david-chapela** [comment]
Extraneous delays cannot be integrated into PIX-framework for now because it depends on Prosimos.

However, it makes sense to integrate the rest:
- Batch processing discovery (adding also the batch classes from Simod project).
- Prioritization rules discovery (adding also the prioritization classes from Simod project).
- Case attribute discovery.
- Start time estimator (could also be easily paralelized when it goes trace by trace, event by event to set the enabled time, or the resource availability).
