### ISSUE TITLE
Negative pending_duration, total_duration, and index in RCalendar. _find_time_completion for BPIC15_1

### ISSUE THREAD

**Issue by iharsuvorau** [AutomatedProcessImprovement/pix-framework#6]
`RCalendar. _find_time_completion` fails in this test case, https://github.com/AutomatedProcessImprovement/pix-framework/blob/bpic15/tests/pix_framework/calendar/test_resource_calendar.py#L385-L395, by having negative pending_duration, total_duration, and index. 

The new test case is in the `bpic15` branch only.

@orlenyslp could you please take a look?

**Comment by orlenyslp** [comment]
I already fixed the bug and pushed the update to the repository. The problem was in the function "generate_sample" in the "distribution" file, which generated a negative number in some cases for some distributions. I added the extra validation, so if the value is negative, the mean value is returned instead, or (max-min) / 2, or 0, depending on whether the corresponding attributes are valid. See the "_replace_negative_value" function on lines 106-113 and the validation on lines 102-103.
